services:
  service_postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    # networks:
    #   - lesson
  service_pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    depends_on:
      - service_postgres
    # networks:
    #   - lesson
networks:
  lesson:
